max_width = 115
short_array_element_width_threshold = 115
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
fn_params_layout = "Compressed"
single_line_if_else_max_width = 115
